name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A clear and concise title for the bug
      placeholder: "e.g., Server crashes when loading invalid markdown"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the codebase is affected?
      options:
        - server.py
        - prompts.py
        - documentation
        - CLI/tooling
        - other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Python version and OS
      placeholder: "e.g., Python 3.11, macOS 14"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what actually happens
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Paste any relevant error messages or logs
      render: shell
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
    validations:
      required: false
