blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/marcmodin/mcp-prompt-server/discussions
    about: Ask questions or discuss ideas in GitHub Discussions
