name: Release Please

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'prompts/**'
      - 'resources/**'
      - '.github/workflows/release-please.yml'
      - 'pyproject.toml'
      - '.python-version'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Use default GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
          # Python release type for proper version management
          release-type: python